import { element, clone } from "./utils";

type Clone = (
  elementToWrap: any
) => (
  className: any,
  ...values: any[]
) => (props: any) => React.FunctionComponentElement<{}>;

interface Static {
  a: any;
  abbr: any;
  acronym: any;
  address: any;
  applet: any;
  area: any;
  article: any;
  aside: any;
  audio: any;
  b: any;
  base: any;
  basefont: any;
  bdi: any;
  bdo: any;
  big: any;
  blockquote: any;
  body: any;
  br: any;
  button: any;
  canvas: any;
  caption: any;
  center: any;
  cite: any;
  code: any;
  col: any;
  colgroup: any;
  data: any;
  datalist: any;
  dd: any;
  del: any;
  details: any;
  dfn: any;
  dialog: any;
  dir: any;
  div: any;
  dl: any;
  dt: any;
  em: any;
  embed: any;
  fieldset: any;
  figcaption: any;
  figure: any;
  font: any;
  footer: any;
  form: any;
  frame: any;
  frameset: any;
  h1: any;
  h2: any;
  h3: any;
  h4: any;
  h5: any;
  h6: any;
  head: any;
  header: any;
  hr: any;
  html: any;
  i: any;
  iframe: any;
  img: any;
  input: any;
  ins: any;
  kbd: any;
  label: any;
  legend: any;
  li: any;
  link: any;
  main: any;
  map: any;
  mark: any;
  meta: any;
  meter: any;
  nav: any;
  noframes: any;
  noscript: any;
  object: any;
  ol: any;
  optgroup: any;
  option: any;
  output: any;
  p: any;
  param: any;
  picture: any;
  pre: any;
  progress: any;
  q: any;
  rp: any;
  rt: any;
  ruby: any;
  s: any;
  samp: any;
  script: any;
  section: any;
  select: any;
  small: any;
  source: any;
  span: any;
  strike: any;
  strong: any;
  style: any;
  sub: any;
  summary: any;
  sup: any;
  svg: any;
  table: any;
  tbody: any;
  td: any;
  template: any;
  textarea: any;
  tfoot: any;
  th: any;
  thead: any;
  time: any;
  title: any;
  tr: any;
  track: any;
  tt: any;
  u: any;
  ul: any;
  var: any;
  video: any;
  wbr: any;
}

type Classy = Clone & Static;

const classy = clone;
classy['a'] = element('a');
classy['abbr'] = element('abbr');
classy['acronym'] = element('acronym');
classy['address'] = element('address');
classy['applet'] = element('applet');
classy['area'] = element('area');
classy['article'] = element('article');
classy['aside'] = element('aside');
classy['audio'] = element('audio');
classy['b'] = element('b');
classy['base'] = element('base');
classy['basefont'] = element('basefont');
classy['bdi'] = element('bdi');
classy['bdo'] = element('bdo');
classy['big'] = element('big');
classy['blockquote'] = element('blockquote');
classy['body'] = element('body');
classy['br'] = element('br');
classy['button'] = element('button');
classy['canvas'] = element('canvas');
classy['caption'] = element('caption');
classy['center'] = element('center');
classy['cite'] = element('cite');
classy['code'] = element('code');
classy['col'] = element('col');
classy['colgroup'] = element('colgroup');
classy['data'] = element('data');
classy['datalist'] = element('datalist');
classy['dd'] = element('dd');
classy['del'] = element('del');
classy['details'] = element('details');
classy['dfn'] = element('dfn');
classy['dialog'] = element('dialog');
classy['dir'] = element('dir');
classy['div'] = element('div');
classy['dl'] = element('dl');
classy['dt'] = element('dt');
classy['em'] = element('em');
classy['embed'] = element('embed');
classy['fieldset'] = element('fieldset');
classy['figcaption'] = element('figcaption');
classy['figure'] = element('figure');
classy['font'] = element('font');
classy['footer'] = element('footer');
classy['form'] = element('form');
classy['frame'] = element('frame');
classy['frameset'] = element('frameset');
classy['h1'] = element('h1');
classy['h2'] = element('h2');
classy['h3'] = element('h3');
classy['h4'] = element('h4');
classy['h5'] = element('h5');
classy['h6'] = element('h6');
classy['head'] = element('head');
classy['header'] = element('header');
classy['hr'] = element('hr');
classy['html'] = element('html');
classy['i'] = element('i');
classy['iframe'] = element('iframe');
classy['img'] = element('img');
classy['input'] = element('input');
classy['ins'] = element('ins');
classy['kbd'] = element('kbd');
classy['label'] = element('label');
classy['legend'] = element('legend');
classy['li'] = element('li');
classy['link'] = element('link');
classy['main'] = element('main');
classy['map'] = element('map');
classy['mark'] = element('mark');
classy['meta'] = element('meta');
classy['meter'] = element('meter');
classy['nav'] = element('nav');
classy['noframes'] = element('noframes');
classy['noscript'] = element('noscript');
classy['object'] = element('object');
classy['ol'] = element('ol');
classy['optgroup'] = element('optgroup');
classy['option'] = element('option');
classy['output'] = element('output');
classy['p'] = element('p');
classy['param'] = element('param');
classy['picture'] = element('picture');
classy['pre'] = element('pre');
classy['progress'] = element('progress');
classy['q'] = element('q');
classy['rp'] = element('rp');
classy['rt'] = element('rt');
classy['ruby'] = element('ruby');
classy['s'] = element('s');
classy['samp'] = element('samp');
classy['script'] = element('script');
classy['section'] = element('section');
classy['select'] = element('select');
classy['small'] = element('small');
classy['source'] = element('source');
classy['span'] = element('span');
classy['strike'] = element('strike');
classy['strong'] = element('strong');
classy['style'] = element('style');
classy['sub'] = element('sub');
classy['summary'] = element('summary');
classy['sup'] = element('sup');
classy['svg'] = element('svg');
classy['table'] = element('table');
classy['tbody'] = element('tbody');
classy['td'] = element('td');
classy['template'] = element('template');
classy['textarea'] = element('textarea');
classy['tfoot'] = element('tfoot');
classy['th'] = element('th');
classy['thead'] = element('thead');
classy['time'] = element('time');
classy['title'] = element('title');
classy['tr'] = element('tr');
classy['track'] = element('track');
classy['tt'] = element('tt');
classy['u'] = element('u');
classy['ul'] = element('ul');
classy['var'] = element('var');
classy['video'] = element('video');
classy['wbr'] = element('wbr');

export default classy as Classy;